version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./sendit-api:/sendit-api
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=fav
      - DB_USER=postgres
      - DB_PASS=
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=fav
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Odin
    ports:
      - "5433:5432"
