# Generated by Django 3.0.2 on 2020-03-28 02:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParcelDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("pickup_location", models.CharField(db_index=True, max_length=255)),
                ("destination", models.CharField(db_index=True, max_length=255)),
                (
                    "present_location",
                    models.CharField(db_index=True, max_length=255, null=True),
                ),
                ("weight", models.IntegerField(db_index=True)),
                ("quote", models.IntegerField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "PENDING"),
                            ("in_transit", "IN_TRANSIT"),
                            ("delivered", "DELIVERED"),
                            ("cancelled", "CANCELLED"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=255,
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=225, unique=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parcel_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"],},  # noqa
        ),
    ]
