name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11

    strategy:
      max-parallel: 4
      matrix:
        python: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python Test Environment
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Test with tox
        run: tox -e py
        env:
          SECRET_KEY: testsecretkey
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
